import { AuthProvider } from "./Provider";
import "../pages/style.css";
import "bootstrap/dist/css/bootstrap.css";
import Header from "@/components/Header";
import Head from "next/head"
import Script from "next/script";


export const metadata = {
  title: "KLF LOAD BOARD",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.ico',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

