import "./style.css";
import { SessionProvider } from "next-auth/react";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import { ChakraProvider } from "@chakra-ui/react";
import MainHeader from "../components/MainHeader";
import StickyHeader from "../components/StickyHeader";
import { useEffect } from "react";




export default function App({
    Component,
    pageProps: { session, ...pageProps },
}) {
    useEffect(() => {
        require("bootstrap/dist/js/bootstrap.bundle.min.js");
      }, []);
    return (
        <>
            <Head>
                <title>Singhfreight Inc</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/icon.ico" />
            </Head>
            <ChakraProvider>
                <SessionProvider session={session}>
                    <MainHeader />
                    <StickyHeader />
                    <Component {...pageProps} />
                </SessionProvider>
            </ChakraProvider>
        </>
    );
}
