import "./style.css";
import { SessionProvider } from "next-auth/react";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import Header from "../components/MainHeader";
import { ChakraProvider } from "@chakra-ui/react";
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })


export default function App({
    Component,
    pageProps: { session, ...pageProps },
}) {
    return (
        <>
            <Head>
                <title>Singhfreight Inc</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/icon.ico" />
            </Head>
            <ChakraProvider>
                <SessionProvider session={session}>
                    <Header />
                    <Component {...pageProps} />
                </SessionProvider>
            </ChakraProvider>
        </>
    );
}
